### PR TITLE
fix(reconciler): map k8s pod phases

### LINKED ISSUE #96: workloadStatusFromInspect missing k8s pod phase mappings
## User Request

Reconciler logs `unknown runner state "failed"` for agent workloads in k8s. Pod phases are not mapped to workload statuses.

### Problem
`workloadStatusFromInspect` in `internal/reconciler/status.go` only handles Docker container states (`running`, `created`, `exited`, `dead`, etc.). The k8s-runner's `InspectWorkload` returns Kubernetes pod phases: `pending`, `running`, `succeeded`, `failed`, `unknown`.

When a pod enters `Failed` phase, the orchestrator can't map it → logs warning and skips status update → workload stuck in stale state, preventing cleanup.

### Fix
Add Kubernetes pod phase mappings to `workloadStatusFromInspect`:

```go
case "pending":
    return runnersv1.WorkloadStatus_WORKLOAD_STATUS_STARTING, nil
case "succeeded":
    return runnersv1.WorkloadStatus_WORKLOAD_STATUS_STOPPED, nil
case "failed":
    return runnersv1.WorkloadStatus_WORKLOAD_STATUS_FAILED, nil
case "unknown":
    return runnersv1.WorkloadStatus_WORKLOAD_STATUS_UNSPECIFIED, fmt.Errorf("pod phase unknown for workload")
```

Note: `running` is already handled by existing Docker mapping.

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- map Kubernetes pod phases in workload status mapping
- extend test fakes with image pull secret RPC stubs

## Testing
- go test ./...
- go vet ./...

Closes #96

### CODE REVIEW

File: internal/reconciler/status.go [hunk 1]
```diff
@@ -78,6 +78,14 @@ func workloadStatusFromInspect(resp *runnerv1.InspectWorkloadResponse) (runnersv
 		return runnersv1.WorkloadStatus_WORKLOAD_STATUS_STARTING, nil
 	case dockerStatePaused:
 		return runnersv1.WorkloadStatus_WORKLOAD_STATUS_RUNNING, nil
+	case "pending":
```
Comment (noa-lucent) [inline internal/reconciler/status.go]: [major] The new k8s pod phases are bare string literals, while all Docker states use named constants (e.g. `dockerStateRunning`). This is inconsistent and introduces magic strings into internal logic.

Define constants following the existing naming convention:

```go
const (
    k8sPhasePending   = "pending"
    k8sPhaseSucceeded = "succeeded"
    k8sPhaseFailed    = "failed"
    k8sPhaseUnknown   = "unknown"
)
```

Then use them in the switch cases.

**Review by noa-lucent — DISMISSED** [review]
All prior feedback addressed and verified in code:

1. **Named constants** — `k8sPhase*` constants defined and used consistently with the existing `dockerState*` pattern.
2. **Test coverage** — Four new table-driven cases in `TestWorkloadStatusFromInspect` covering `pending`, `succeeded`, `failed`, and `unknown` (with error assertion).
3. **Consolidated fakes** — `internal/testutil/fake_clients.go` is now the single source of truth; duplicate stubs removed from both test files.

Clean change, resolves #96. LGTM.
