### PR TITLE
fix(reconciler): ignore missing workloads

### LINKED ISSUE #130: StopWorkload fails due to double "workload-" prefix from runner instance_id
## User request
Orchestrator can’t reliably terminate workloads/activities. Observed logs:

```text
reconciler: cycle complete - desired=0 actual=3 started=0 stopped=3
reconciler: stop workload <id>: rpc error: code = NotFound desc = resource not found: pods "workload-workload-..." not found
```

### Actual root cause
In the k8s-runner backend:
- Workload pods are named `workload-<workload_uuid>`.
- `Runner.StopWorkload` expects `workload_id = <workload_uuid>` and then prefixes `workload-` internally.
- However, `Runner.ListWorkloads` returns `WorkloadListItem.instance_id = pod.Name` (i.e. `workload-<workload_uuid>`).

In the orchestrator:
- The workload reconciliation loop persisted that `instance_id` value into the workload record.
- Later, `stopWorkload` passed the stored `instance_id` back to `Runner.StopWorkload`.
- The runner then prefixed again, producing `workload-workload-<uuid>` → pod not found → stop never completes.

### Required behavior
- Orchestrator must store and pass the canonical runner workload id (UUID) to runner RPCs.
- Stopping should remain idempotent: if the runner returns `NotFound` for a *valid UUID* workload id, treat as success and proceed with cleanup.

### Required changes
- Normalize runner instance IDs at boundaries:
  - Convert `workload-<uuid>` → `<uuid>` when ingesting `WorkloadListItem.instance_id` (and when using any stored legacy values).
  - Also normalize `StartWorkloadResponse.id` defensively.
- Use the normalized UUID everywhere we call `Runner.StopWorkload`.
- Keep `codes.NotFound` as success **only when the argument is a valid UUID** (do not mask malformed/prefixed IDs).

### Tests
- Table-driven unit tests for the normalizer.
- Lifecycle tests ensuring:
  - `workload-<uuid>` is normalized before StopWorkload
  - NotFound is treated as success for valid UUIDs
  - NotFound is *not* swallowed for invalid/non-UUID IDs

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- normalize runner workload instance IDs at start/stop boundaries
- treat StopWorkload NotFound as success only for valid UUIDs
- add tests for normalization and NotFound handling

## Testing
- GOMAXPROCS=2 go vet -p 1 ./...
- GOMAXPROCS=2 go test -p 1 ./...

Fixes #130

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Test & Lint Summary
- Lint: GOMAXPROCS=2 go vet -p 1 ./... (no errors)
- Tests: GOMAXPROCS=2 go test -p 1 ./... (passed: all, failed: 0, skipped: 0)

**Review by noa-lucent — DISMISSED** [review]
Clean, minimal fix that correctly addresses #130.

**Production code:** `stopRunnerWorkload` now short-circuits on `nil` error and treats `codes.NotFound` as success, propagating all other errors. Idiomatic Go, no unnecessary defensive logic.

**Tests:** Both the NotFound-as-success path and the error-propagation path are well covered. Request parameters (workload ID, timeout) are validated in the test fakes.

LGTM.

**Comment by casey-brooks** [comment]
## Test & Lint Summary
- Lint: GOMAXPROCS=2 go vet -p 1 ./... (no errors)
- Tests: GOMAXPROCS=2 go test -p 1 ./... (passed: all, failed: 0, skipped: 0)

File: internal/reconciler/workload_id.go [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+import (
+	"strings"
+
+	"github.com/google/uuid"
+)
+
+const runnerWorkloadPrefix = "workload-"
+
+func normalizeRunnerWorkloadID(instanceID string) string {
```
Comment (noa-lucent) [inline internal/reconciler/workload_id.go:11]: [major] Normalizing on every read is fragile — it scatters the fix across multiple call sites and leaves two paths that still pass the raw prefixed ID to `stopRunnerWorkload`:

- `reconciler.go` L244: `instanceID := resp.GetId()` → `stopRunnerWorkload(ctx, runnerClient, instanceID)` (failure path)
- `reconciler.go` L265: same pattern (status-map failure path)
- `reconciler.go` L275: the prefixed value is stored in the DB as-is

Normalize once at the boundary — right when `resp.GetId()` is received from the runner — so the canonical internal type is always a clean UUID. That way every downstream consumer (stop, store, reconcile) works with the correct value without needing to remember to call `normalizeRunnerWorkloadID`.

Concretely, add the normalization at the three `resp.GetId()` assignments in `reconciler.go` (L244, L265, L275) and remove the `normalizeRunnerWorkloadID` calls from `stopWorkload`, `reconcileWorkloads`, and `handlePresentRunnerWorkload`. This follows the boundary/internal separation: parse once at the edge, trust the value everywhere else.

File: internal/reconciler/workload_id.go [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+	}
+	trimmed := strings.TrimPrefix(instanceID, runnerWorkloadPrefix)
+	if trimmed == "" {
+		return instanceID
+	}
+	if _, err := uuid.Parse(trimmed); err != nil {
+		return instanceID
+	}
+	return trimmed
+}
```
Comment (noa-lucent) [inline internal/reconciler/workload_id.go:23]: [major] This function needs its own unit tests. It's a pure function with several branches (no prefix, empty after trim, invalid UUID after trim, valid UUID after trim) — each deserves a test case. A table-driven test would be concise and cover all paths.

File: internal/reconciler/reconciler.go [hunk 3]
```diff
@@ -292,7 +292,7 @@ func (r *Reconciler) stopWorkload(ctx context.Context, workload *runnersv1.Workl
 		log.Printf("reconciler: workload missing id")
 		return
 	}
-	instanceID := workload.GetInstanceId()
+	instanceID := normalizeRunnerWorkloadID(workload.GetInstanceId())
```
Comment (noa-lucent) [inline internal/reconciler/reconciler.go:296]: [major] The linked issue (#130) explicitly requires idempotent stop behavior:

> Stopping a workload should be **idempotent**: if the runner reports the pod is already gone (`NotFound`), the orchestrator should treat that as success and continue cleanup.

Normalizing the ID fixes the *root cause* of the observed `NotFound`, but doesn't make the operation idempotent. A pod can legitimately be gone for other reasons (node failure, manual deletion, GC). Without the `codes.NotFound` → `return nil` guard in `stopRunnerWorkload`, those cases will still cause the orchestrator to skip marking the workload as stopped and potentially leak identities — exactly the bug described in the issue.

Please restore the NotFound handling in `stopRunnerWorkload` alongside the normalization fix. Both are needed: normalization prevents the double-prefix, and NotFound-as-success provides the idempotency guarantee.

**Review by noa-lucent — CHANGES_REQUESTED** [review]
The new normalization approach addresses the root cause of the double-prefix bug — good direction. However, three issues need to be resolved before merging:

1. **Normalize at the boundary, not on every read.** The current approach scatters `normalizeRunnerWorkloadID` across read sites but misses two `resp.GetId()` paths in `reconciler.go` that pass the raw prefixed ID directly to `stopRunnerWorkload`. Normalize once when the ID enters the system.

2. **Restore the NotFound idempotency guard.** The issue explicitly requires `stopRunnerWorkload` to treat `codes.NotFound` as success. Normalization alone doesn't cover pods that are legitimately gone (node failure, manual deletion, etc.).

3. **Add unit tests for `normalizeRunnerWorkloadID`.** A pure function with multiple branches needs direct test coverage.

**Comment by casey-brooks** [comment]
## Test & Lint Summary
- Lint: GOMAXPROCS=2 go vet -p 1 ./... (no errors)
- Tests: GOMAXPROCS=2 go test -p 1 ./... (passed: all, failed: 0, skipped: 0)

**Review by noa-lucent — APPROVED** [review]
All three prior issues are resolved. Clean update.

1. **Boundary normalization** — `resp.GetId()` is now normalized once at the boundary (L244-245 in `reconciler.go`), and both failure paths use the normalized value. The `workload_reconcile.go` and `stopWorkload` normalizations on runner list responses / stored records are correct since those are separate entry points.

2. **NotFound idempotency restored** — `stopRunnerWorkload` treats `codes.NotFound` as success for valid UUIDs, while surfacing it for malformed IDs. Reasonable safety net without violating internal-code principles.

3. **Unit tests added** — `workload_id_test.go` covers all branches via a clean table-driven test. Three lifecycle tests cover NotFound-for-UUID, NotFound-for-invalid-ID, and generic error propagation.

LGTM.
