### PR TITLE
Require explicit init images

### LINKED ISSUE #106: Remove DEFAULT_INIT_IMAGE fallback; make init_image required; add agn pipeline e2e test
## User Request

Two changes requested:

1. **Remove `DEFAULT_INIT_IMAGE` parameter** from the orchestrator. The `init_image` field on the Agent resource should be treated as required — the assembler must not silently fall back to a default. If `init_image` is empty, the assembler should return an error.

2. **Add a new e2e test** that runs the full pipeline (`thread → orchestrator → agent → thread`) using the **agn** agent, mirroring the existing `TestFullPipelineMessageResponse` which uses Codex.

### Task 1: Remove `DEFAULT_INIT_IMAGE` fallback

**Files to change:**

#### `internal/assembler/assembler.go`
- Lines 112–114: Replace the fallback logic:
  ```go
  initImage := agent.GetInitImage()
  if initImage == "" {
      initImage = a.cfg.DefaultInitImage
  }
  ```
  With a hard error:
  ```go
  initImage := agent.GetInitImage()
  if initImage == "" {
      return nil, fmt.Errorf("agent %s: init_image is required", agentID)
  }
  ```

#### `internal/config/config.go`
- Remove the `DefaultInitImage` field from the `Config` struct (line 23).
- Remove the `DEFAULT_INIT_IMAGE` env var parsing (lines 121–123).

#### `internal/config/config_test.go`
- Remove `t.Setenv("DEFAULT_INIT_IMAGE", "init-image")` from `setBaseEnv` helper.

#### `internal/assembler/assembler_test.go`
- Remove all `DefaultInitImage: "default-init-image"` from test config literals (appears ~12 times).
- In `TestAssemblerMainContainer`: The current test uses an agent **without** `InitImage` set and expects it to fall back to `cfg.DefaultInitImage`. This test should now set `InitImage` on the agent to a non-empty value and assert the init container uses that image. Remove assertions that reference `cfg.DefaultInitImage`.
- In `TestAssemblerInitImageOverride`: This test already sets `InitImage: "agent-init-image"` on the agent. No logic change needed, just remove `DefaultInitImage` from config.
- Add a **new unit test** `TestAssemblerErrorsOnEmptyInitImage` that creates an agent with `InitImage: ""` and asserts that `Assemble` returns an error containing `"init_image is required"`.
- All other assembler tests that construct a `config.Config{}` must remove the `DefaultInitImage` field. Ensure the agents in those tests have `InitImage` set to a non-empty value so they don't trigger the new error.

#### `charts/agents-orchestrator/values.yaml`
- Remove the `DEFAULT_INIT_IMAGE` env var entry (lines 87–88).

#### `test/e2e/main_test.go`

Add two new env-backed constants for init images used in e2e:
```go
var (
    codexInitImage = envOrDefault("CODEX_INIT_IMAGE", "ghcr.io/agynio/agent-init-codex:latest")
    agnInitImage   = envOrDefault("AGN_INIT_IMAGE", "ghcr.io/agynio/agent-init-agn:latest")
)
```

Add a second TestLLM endpoint constant for agn:
```go
const (
    testLLMEndpointCodex = "https://testllm.dev/v1/org/agynio/suite/codex/responses"
    testLLMEndpointAgn   = "https://testllm.dev/v1/org/agynio/suite/agn/responses"
)
```
Rename the existing `testLLMEndpoint` to `testLLMEndpointCodex` (update all references).

Update `createAgent` helper to accept `initImage` parameter:
```go
func createAgent(t *testing.T, ctx context.Context, client agentsv1.AgentsServiceClient, name, model, organizationID, initImage string) *agentsv1.Agent {
    // ...
    resp, err := client.CreateAgent(ctx, &agentsv1.CreateAgentRequest{
        Name:           name,
        Role:           "assistant",
        Model:          model,
        Image:          "alpine:3.21",
        InitImage:      initImage,
        OrganizationId: organizationID,
    })
    // ...
}
```

#### All existing e2e test files
Update all `createAgent` calls to pass `codexInitImage` as the `initImage` argument and use `testLLMEndpointCodex` instead of `testLLMEndpoint`. Affected files:
- `test/e2e/start_test.go`
- `test/e2e/dedup_test.go`
- `test/e2e/idle_test.go`
- `test/e2e/multi_test.go`
- `test/e2e/pipeline_test.go`
- `test/e2e/mcp_test.go`
- `test/e2e/imagepull_test.go`

#### `test/e2e/pipeline_test.go`

Add `TestFullPipelineAgnMessageResponse` — same structure as `TestFullPipelineMessageResponse` but:
- Uses `testLLMEndpointAgn` for the LLM provider endpoint
- Uses `agnInitImage` for the agent's init image
- Model `remoteName` is `"simple-hello"` (same name, different suite)
- Sends message `"hi"` (not `"hello"` — agn's `simple-hello` test expects `"hi"`)
- Asserts agent response is `"Hi! How are you?"` (same expected response)

## Reference

- TestLLM agn suite: `agynio/testllm-suites/agn.tf` — `simple-hello` test expects input `role: "user", content: "hi"` → output `"Hi! How are you?"`
- TestLLM codex suite: `agynio/testllm-suites/codex.tf` — `simple-hello` test expects input `role: "user", content: "hello"` → output `"Hi! How are you?"`
- Init images: `ghcr.io/agynio/agent-init-codex:latest`, `ghcr.io/agynio/agent-init-agn:latest`
- Architecture: `agynio/architecture/architecture/agent-init.md`, `agynio/architecture/architecture/operations/e2e-testing.md`

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- remove DEFAULT_INIT_IMAGE fallback and enforce init_image on agents
- update e2e helpers/tests to pass init images and add agn pipeline coverage
- refactor pipeline e2e into shared helper for codex/agn
- isolate ziti management fake CreateService stub in its own commit

## Testing
- go test ./...
- go vet ./...
- go test ./test/e2e -tags e2e -run TestDoesNotExist

Closes #106

### CODE REVIEW

File: internal/reconciler/lifecycle_test.go [hunk 1]
```diff
@@ -900,6 +899,7 @@ func (f *fakeRunnerClient) CancelExecution(context.Context, *runnerv1.CancelExec
 type fakeZitiMgmtClient struct {
 	createAgentIdentity    func(context.Context, *zitimgmtv1.CreateAgentIdentityRequest, ...grpc.CallOption) (*zitimgmtv1.CreateAgentIdentityResponse, error)
 	createAppIdentity      func(context.Context, *zitimgmtv1.CreateAppIdentityRequest, ...grpc.CallOption) (*zitimgmtv1.CreateAppIdentityResponse, error)
+	createService          func(context.Context, *zitimgmtv1.CreateServiceRequest, ...grpc.CallOption) (*zitimgmtv1.CreateServiceResponse, error)
```
Comment (noa-lucent) [inline internal/reconciler/lifecycle_test.go]: [nit] The `createService` field and method on `fakeZitiMgmtClient` are unrelated to issue #106 — this looks like a compile-fix for an updated proto interface. Consider splitting it into a separate commit or PR for traceability.

**Review by vitramir — APPROVED** [review]
